import {defineField, defineType, defineArrayMember} from 'sanity'

export const homePage = defineType({
  name: 'homePage',
  title: 'Home Page',
  type: 'document',
  fieldsets: [
    {name: 'hero', title: 'Hero banner', options: {collapsible: true, collapsed: false}},
    {name: 'floatingActions', title: 'Floating buttons', options: {collapsible: true, collapsed: true}},
    {name: 'programs', title: 'B.Tech programs', options: {collapsible: true, collapsed: true}},
    {name: 'highlights', title: 'College highlights', options: {collapsible: true, collapsed: true}},
    {name: 'achievements', title: 'Achievements', options: {collapsible: true, collapsed: true}},
    {name: 'placements', title: 'Placements', options: {collapsible: true, collapsed: true}},
    {name: 'campusLife', title: 'Life at VKCET', options: {collapsible: true, collapsed: true}},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Document title',
      type: 'string',
      initialValue: 'Home Page',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'heroTitle',
      title: 'Hero title',
      type: 'string',
      fieldset: 'hero',
    }),
    defineField({
      name: 'heroSubtitle',
      title: 'Hero subtitle',
      type: 'text',
      rows: 3,
      fieldset: 'hero',
    }),
    defineField({name: 'heroKicker', title: 'Hero eyebrow', type: 'string', fieldset: 'hero'}),
    defineField({
      name: 'ctaLabel',
      title: 'Call-to-action label',
      type: 'string',
      fieldset: 'hero',
    }),
    defineField({
      name: 'ctaLink',
      title: 'Call-to-action link',
      description: 'Can be an internal path or an external URL.',
      type: 'string',
      fieldset: 'hero',
    }),
    defineField({
      name: 'heroSlides',
      title: 'Hero slides',
      type: 'array',
      fieldset: 'hero',
      of: [
        defineArrayMember({
          name: 'heroSlide',
          title: 'Slide',
          type: 'object',
          fields: [
            defineField({name: 'image', title: 'Image', type: 'image', options: {hotspot: true}, validation: (Rule) => Rule.required()}),
            defineField({name: 'alt', title: 'Alternative text', type: 'string'}),
          ],
          preview: {select: {title: 'alt', media: 'image'}},
        }),
      ],
    }),
    defineField({name: 'heroIntervalMs', title: 'Slide duration (milliseconds)', type: 'number', fieldset: 'hero', initialValue: 4500, validation: (Rule) => Rule.min(1500)}),
    defineField({name: 'heroAutoplay', title: 'Automatically advance slides', type: 'boolean', fieldset: 'hero', initialValue: true}),
    defineField({
      name: 'featuredPrograms',
      title: 'Featured programs',
      type: 'array',
      of: [
        defineArrayMember({
          name: 'program',
          title: 'Program',
          type: 'object',
          fields: [
            defineField({name: 'title', title: 'Title', type: 'string', validation: (Rule) => Rule.required()}),
            defineField({name: 'description', title: 'Description', type: 'text', rows: 2}),
            defineField({
              name: 'href',
              title: 'Link',
              description: 'Can be an internal path or an external URL.',
              type: 'string',
            }),
          ],
          preview: {select: {title: 'title', subtitle: 'description'}},
        }),
      ],
    }),
    defineField({
      name: 'floatingActions',
      title: 'Floating button settings',
      type: 'object',
      fieldset: 'floatingActions',
      fields: [
        defineField({
          name: 'seatBooking',
          title: 'Seat booking pill',
          type: 'object',
          fields: [
            defineField({name: 'enabled', title: 'Show seat booking button', type: 'boolean', initialValue: true}),
            defineField({name: 'eyebrow', title: 'Eyebrow', type: 'string'}),
            defineField({name: 'line1', title: 'First line', type: 'string'}),
            defineField({name: 'line2', title: 'Second line', type: 'string'}),
            defineField({name: 'href', title: 'Destination URL', type: 'url'}),
          ],
        }),
        defineField({
          name: 'socialLinks',
          title: 'Floating social and utility links',
          type: 'object',
          fields: [
            defineField({name: 'defaultExpanded', title: 'Expanded by default', type: 'boolean', initialValue: true}),
            defineField({name: 'whatsappHref', title: 'WhatsApp URL', type: 'url'}),
            defineField({name: 'instagramHref', title: 'Instagram URL', type: 'url'}),
            defineField({name: 'youtubeHref', title: 'YouTube URL', type: 'url'}),
            defineField({name: 'linwaysHref', title: 'Linways URL', type: 'url'}),
            defineField({name: 'mapsHref', title: 'Google Maps URL', type: 'url'}),
          ],
        }),
      ],
    }),
    defineField({name: 'programsKicker', title: 'Section eyebrow', type: 'string', fieldset: 'programs'}),
    defineField({name: 'programsTitle', title: 'Section title', type: 'string', fieldset: 'programs'}),
    defineField({name: 'programsViewAllLabel', title: 'View-all button label', type: 'string', fieldset: 'programs'}),
    defineField({name: 'programsViewAllHref', title: 'View-all destination', type: 'string', fieldset: 'programs'}),
    defineField({
      name: 'programs',
      title: 'B.Tech program cards',
      type: 'array',
      fieldset: 'programs',
      of: [
        defineArrayMember({
          name: 'programCard',
          title: 'Program',
          type: 'object',
          fields: [
            defineField({name: 'title', title: 'Program name', type: 'string', validation: (Rule) => Rule.required()}),
            defineField({name: 'href', title: 'Program page URL', type: 'string'}),
            defineField({name: 'content', title: 'Card detail (e.g. seats)', type: 'string'}),
            defineField({name: 'icon', title: 'Card icon', type: 'string', options: {list: ['cse', 'cyber', 'civil', 'eee', 'ece', 'mech']}}),
            defineField({name: 'styleClass', title: 'Card style', type: 'string', options: {list: ['style1', 'style2']}, initialValue: 'style1'}),
            defineField({name: 'backgroundImage', title: 'Card image', type: 'image', options: {hotspot: true}}),
          ],
          preview: {select: {title: 'title', subtitle: 'content', media: 'backgroundImage'}},
        }),
      ],
    }),
    defineField({
      name: 'highlights',
      title: 'Highlight cards',
      type: 'array',
      fieldset: 'highlights',
      of: [defineArrayMember({type: 'string', name: 'highlight', title: 'Highlight'})],
    }),
    defineField({name: 'achievementsTitle', title: 'Section title', type: 'string', fieldset: 'achievements'}),
    defineField({
      name: 'achievements',
      title: 'Achievement counters',
      type: 'array',
      fieldset: 'achievements',
      of: [
        defineArrayMember({
          name: 'achievement',
          title: 'Achievement',
          type: 'object',
          fields: [
            defineField({name: 'key', title: 'Stable key', type: 'string', validation: (Rule) => Rule.required()}),
            defineField({name: 'label', title: 'Label', type: 'string', validation: (Rule) => Rule.required()}),
            defineField({name: 'value', title: 'Counter value', type: 'number', validation: (Rule) => Rule.required().min(0)}),
            defineField({name: 'suffix', title: 'Suffix', type: 'string'}),
          ],
          preview: {select: {title: 'label', subtitle: 'value'}},
        }),
      ],
    }),
    defineField({name: 'placementsTitle', title: 'Section title', type: 'string', fieldset: 'placements'}),
    defineField({
      name: 'placementRecruiters',
      title: 'Recruiter logos',
      type: 'array',
      fieldset: 'placements',
      of: [
        defineArrayMember({
          name: 'recruiter',
          title: 'Recruiter',
          type: 'object',
          fields: [
            defineField({name: 'name', title: 'Company name', type: 'string', validation: (Rule) => Rule.required()}),
            defineField({name: 'logo', title: 'Logo', type: 'image', options: {hotspot: true}, validation: (Rule) => Rule.required()}),
          ],
          preview: {select: {title: 'name', media: 'logo'}},
        }),
      ],
    }),
    defineField({
      name: 'placementStats',
      title: 'Placement highlights',
      type: 'array',
      fieldset: 'placements',
      of: [
        defineArrayMember({
          name: 'placementStat',
          title: 'Statistic',
          type: 'object',
          fields: [
            defineField({name: 'value', title: 'Value', type: 'string', validation: (Rule) => Rule.required()}),
            defineField({name: 'label', title: 'Label', type: 'string', validation: (Rule) => Rule.required()}),
          ],
          preview: {select: {title: 'value', subtitle: 'label'}},
        }),
      ],
    }),
    defineField({name: 'placementCtaLabel', title: 'Placement report button label', type: 'string', fieldset: 'placements'}),
    defineField({name: 'placementCtaHref', title: 'Placement report URL', type: 'url', fieldset: 'placements'}),
    defineField({name: 'lifeAtVkcetTitle', title: 'Section title', type: 'string', fieldset: 'campusLife'}),
    defineField({name: 'lifeAtVkcetCtaLabel', title: 'Gallery button label', type: 'string', fieldset: 'campusLife'}),
    defineField({name: 'lifeAtVkcetCtaHref', title: 'Gallery destination', type: 'string', fieldset: 'campusLife'}),
    defineField({
      name: 'lifeAtVkcetCards',
      title: 'Campus-life image cards',
      description: 'Add up to four cards, with several images per card for the slideshow.',
      type: 'array',
      fieldset: 'campusLife',
      of: [
        defineArrayMember({
          name: 'campusLifeCard',
          title: 'Campus-life card',
          type: 'object',
          fields: [
            defineField({
              name: 'images',
              title: 'Slideshow images',
              type: 'array',
              of: [defineArrayMember({type: 'image', options: {hotspot: true}})],
            }),
          ],
          preview: {select: {media: 'images.0'}},
        }),
      ],
    }),
  ],
  preview: {select: {title: 'title'}},
})